x-app: &app
  build:
    context: .
    dockerfile: docker/Dockerfile
  working_dir: /app/src
  volumes:
    - .:/app
    - ./static:/app/static
  depends_on:
    - db
    - redis

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static
    depends_on:
      - web
      - api

  redis:
    image: redis:latest

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_db

  web:
    <<: *app
    ports:
      - "8001:8001"
#    command: gunicorn core.wsgi -b 0.0.0.0:8001
    command: python manage.py runserver 0.0.0.0:8001

  api:
    <<: *app
    ports:
      - "8002:8002"
    command: gunicorn api.main:app -b 0.0.0.0:8002 -k uvicorn_worker.UvicornWorker
    entrypoint: []

  worker-beat:
    <<: *app
    command: celery -A core worker -l info -B
    ports: []
    entrypoint: []

volumes:
  postgres_data:
